name: cone_lib
description: Library for cone app
homepage: https://github.com/bradyt/cone

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  built_value:
  intl:
  petitparser:

dev_dependencies:
  build_runner:
  built_value_generator:
  test:
